// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTlxbiKj5XsQHZP6H4WqYL6glM0jMy1bU',
    appId: '1:25737732700:web:af97628748a7b08b007c99',
    messagingSenderId: '25737732700',
    projectId: 'college-competitions',
    authDomain: 'college-competitions.firebaseapp.com',
    storageBucket: 'college-competitions.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1rwOL6tBcKilUwjPPxycqsx1o9Cgk1Q',
    appId: '1:25737732700:android:e50fff5d30615034007c99',
    messagingSenderId: '25737732700',
    projectId: 'college-competitions',
    storageBucket: 'college-competitions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQujWGLpmZUrCw9ddEUB2wmYm5CQ6vrII',
    appId: '1:25737732700:ios:2e18df3db5d2fb42007c99',
    messagingSenderId: '25737732700',
    projectId: 'college-competitions',
    storageBucket: 'college-competitions.appspot.com',
    iosClientId: '25737732700-daugolvtpo2dbomnqmkk33236h07hbg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeCompetitions',
  );
}
